language: node_js
node_js: '10'
cache: yarn

install:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      yarn install --immutable --immutable-cache
    else
      yarn install --immutable --immutable-cache --check-cache
    fi

script: 
  - yarn dist

after_success:
  - mkdir dist/docs/dist && cp -R dist/browser/* dist/docs/dist

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: release
  - provider: npm
    skip-cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: release
      tags: true